// Post-build checks over the generated site. Exits 1 on any failure.
//
//   npm run check        (run after npm run build)
//
// Catches the regressions that used to slip through when every page was
// hand-edited: broken links and anchors, missing titles/descriptions/
// canonicals, stray template tokens, the GA placeholder, links to deleted
// prototype pages, invalid JSON-LD, duplicate ids, and hand-written HTML at
// the root that the build doesn't own.

import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Root HTML files the build intentionally doesn't own.
const NOT_GENERATED = new Set(['map-prototype-maplibre.html']);

const files = [
  ...readdirSync(ROOT).filter((f) => f.endsWith('.html')).map((f) => join(ROOT, f)),
  ...(existsSync(join(ROOT, 'lawn-mowing'))
    ? readdirSync(join(ROOT, 'lawn-mowing')).filter((f) => f.endsWith('.html')).map((f) => join(ROOT, 'lawn-mowing', f))
    : [])
];

const failures = [];
const fail = (file, msg) => failures.push(relative(ROOT, file).split(sep).join('/') + ': ' + msg);
const cache = new Map();
const readPage = (file) => {
  if (!cache.has(file)) cache.set(file, readFileSync(file, 'utf8'));
  return cache.get(file);
};
const idsIn = (html) => new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));

let checked = 0;
for (const file of files) {
  const name = relative(ROOT, file).split(sep).join('/');
  if (NOT_GENERATED.has(name)) continue;
  const html = readPage(file);

  if (!html.slice(0, 400).includes('GENERATED by scripts/build.mjs')) {
    fail(file, 'not generated by the build — move it into src/pages or delete it');
    continue;
  }
  checked++;

  const noindex = /<meta name="robots" content="[^"]*noindex/.test(html);
  const h1s = (html.match(/<h1[\s>]/g) || []).length;
  if (h1s !== 1) fail(file, 'expected exactly one <h1>, found ' + h1s);
  if (!/<title>[^<]+<\/title>/.test(html)) fail(file, 'missing <title>');
  if (!/<meta name="description" content="[^"]+">/.test(html)) fail(file, 'missing meta description');
  if (!noindex && !/<link rel="canonical" href="https:\/\/[^"]+">/.test(html)) fail(file, 'missing canonical URL');
  if (html.includes('{{')) fail(file, 'unrendered {{ token');
  if (html.includes('G-XXXXXXXXXX')) fail(file, 'GA placeholder id emitted');
  if (/-prototype\.html/.test(html)) fail(file, 'links to a deleted prototype page');

  for (const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    try { JSON.parse(m[1]); } catch (err) { fail(file, 'invalid JSON-LD: ' + err.message); }
  }

  const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length) fail(file, 'duplicate id(s): ' + [...new Set(dupes)].join(', '));

  for (const m of html.matchAll(/\s(?:href|src)="([^"]*)"/g)) {
    const url = m[1];
    if (!url) { fail(file, 'empty href/src'); continue; }
    if (/^(https?:|\/\/|mailto:|tel:|data:|javascript:)/.test(url)) continue;
    const [pathAndQuery, hash] = url.split('#');
    const path = pathAndQuery.split('?')[0];
    let target = file;
    if (path) {
      target = path.startsWith('/') ? join(ROOT, path) : join(dirname(file), path);
      if (path.endsWith('/')) target = join(target, 'index.html');
      if (!existsSync(target)) { fail(file, 'broken link: ' + url); continue; }
    }
    if (hash && target.endsWith('.html') && !idsIn(readPage(target)).has(hash)) {
      fail(file, 'broken anchor: ' + url);
    }
  }
}

const sitemap = readFileSync(join(ROOT, 'sitemap.xml'), 'utf8');
for (const m of sitemap.matchAll(/<loc>https:\/\/thelawncare\.com\.au\/([^<]*)<\/loc>/g)) {
  const path = m[1] || 'index.html';
  if (!existsSync(join(ROOT, path))) failures.push('sitemap.xml: ' + path + ' does not exist');
}

if (failures.length) {
  console.error(failures.map((f) => '  ✖ ' + f).join('\n'));
  console.error('\n' + failures.length + ' problem(s) across ' + checked + ' generated page(s).');
  process.exit(1);
}
console.log('✔ ' + checked + ' generated pages passed all checks.');
